### ISSUE TITLE
"Your ESP8266 board is not supported." when using the web-flasher and wemos D1 mini module

### ISSUE THREAD

**Issue by Roellen** [frickelzeugs/FingerprintDoorbell#104]
Hi. 

I tried to use the web flasher app: https://frickelzeugs.github.io/FingerprintDoorbell-flasher/

When connecting to my Wemos D1 mini module it seems to connect (as the com port is shown), but then there is an error message:

**Your ESP8266 board is not supported.**

What can I do? Which ESP board will work?

**Comment by Roellen** [comment]
I tried another computer, another wemos D1, another cable... but still the same error message. 

I tried "Tasmotizer" to flash the *.bin file... but I can't see wifi hotspot

Then I tried the ESP tool, but also no luck. It finished the process, but no wifi hotspot aswell. 
![esp tool](https://github.com/user-attachments/assets/62322923-9a9d-4bf0-9d84-ca5938fe3379)

**Comment by tilly001** [comment]
Hello Roellen,

I use an ESP32 from azdelivery.

Search on Google: esp32 azdelivery

**Comment by Roellen** [comment]
Ha! It works!
I found another ESP32 and this is working fine. 
(I thought it would run on wemos D1 mini, but it does not)
