### ISSUE TITLE
mqtt Port

### ISSUE THREAD

**Issue by Beast-Panik** [frickelzeugs/FingerprintDoorbell#29]
Ich habe versucht in der mqtt Konfiguration den Post zu ändern nach dem Standardformat IP:PORT, das scheint hier nicht zu klappen. Ist es möglich den mqtt Port über die Einstellung in der weboberfläche zu ändern?

**Comment by Beast-Panik** [comment]
Sorry, hab grad erst gesehen das bei den Pullrequests die möglichkeit schon vorgeschalgen wurde :/

**Comment by ZeroQool007** [comment]
Ja, das wäre super. Habe auf dem iobroker MQTT Server laufen der kann nicht auf den Standard-Port 1883 verbinden.
