### ISSUE TITLE
Wechselstrom 12V

### ISSUE THREAD

**Issue by heckmic** [frickelzeugs/FingerprintDoorbell#66]
Bei meiner Klingel kommen Draußen an Knopf 12V Wechselstrom an. 
Muss ich noch eine Diode oder einen Gleichrichter vor den Stepdown (habe den gleichen wie du) setzen?

**Comment by heckmic** [comment]
Habe ein 5V Trafo im Zählerschrank installiert und umgeklemmt.

**Comment by mkrasselt1** [comment]
wenn du das alles so lassen willst, sollte ein Brückengleichrichter (oder 4 Dioden im Kreis) ausreichend sein, auf der Eingangsseite vom Stepdown Regler
