### ISSUE TITLE
Micro JST SH löten?

### ISSUE THREAD

**Issue by hesne** [frickelzeugs/FingerprintDoorbell#85]
Hallo zusammen, 
könnt ihr mir bitte verraten wir ihr die Micro JST SH gelötet bekommt? Bei mir halten die Kabel auf den Pins einfach nicht.

**Comment by Spont09** [comment]
Hab bei eBay folgenden Artikel gekauft 

✅ Micro JST SH 1.0 2P 3P 4Pin 5Pin 6PIN Male Female Stecker Buchse Kupplung 15cm

Eventuell hilft dir das weiter
