### ISSUE TITLE
Connection 38 pin board

### ISSUE THREAD

**Issue by xxbyxx** [frickelzeugs/FingerprintDoorbell#87]
Hi, 

weiß jemand wie die Pin-Belegung am 38pin esp32 aussieht? 
Ich habe hin und her probiert aber der R503 sensor scheint nicht angesprochen zu werden (kein LED Ring und auch keine Reaktion auf das Anlernen neuer Finder im web UI)

p.s. mein R503 hat ein braunes statt grünes Kabel - gibt es da grundsätzlich unterschiedliche Belegung der Kabel in den gängigen Sensoren oder ist das tatsächlich einfach nur eine andere Farbwahl?

Vielen Dank vorab 

![grafik](https://github.com/frickelzeugs/FingerprintDoorbell/assets/58613165/ffafc283-a4b0-4fc7-ac42-d6d784413dd7)

**Comment by xxbyxx** [comment]
I fixed it

**Comment by Noschvie** [comment]
Wie sieht deine Lösung aus?
Für jene, die hier landen und nach einer Antwort suchen...

**Comment by xxbyxx** [comment]
Klar - sorry ich hatte gestern kaum Zeit für eine ausführlichere Antwort. 
Im Grunde muss man nur das GPIO Belegungsschema konsequent auf die 38-Pin-Variante übertragen
Jetzt funktioniert auch die Kommunikation mit dem IO broker

![grafik](https://github.com/frickelzeugs/FingerprintDoorbell/assets/58613165/70689a0f-3680-41b2-b4ef-64cc6c980ffc)
