### ISSUE TITLE
Fingerprint reader only works with shoes on

### ISSUE THREAD

**Issue by DUSAG0211** [frickelzeugs/FingerprintDoorbell#88]
Hey,
not an electrician but apparently the reader only detects presence of my finger if i have shoes on.
If in socks and touching the ground in front of my house the reader does not work.
If i climb on my wooden bench it works again.

Can someone more literate in electric stuff share what i would need to change in my system?

I am powering the device with approx 5.6v from our doorbell wire.
The power comes from a 5v dc adapter in our power box (Meanwell Hutschienen-Adapter)

**Comment by geronet1** [comment]
L & N am Netzteil vertauschen :-)

**Comment by DUSAG0211** [comment]
> L & N am Netzteil vertauschen :-)

Hey, so banal? muss ich mal probieren. Alles andere funktioniert aber, und ich hatte penibel auf die identische Polung Netzteil/ESP geachtet.

**Comment by geronet1** [comment]
Kann gut sein daß da ein Ableitstrom von dem Sensor (GND) über dich auf Erde läuft und er den Finger dadurch nicht erkennt.
Evtl. auch anderes Netzteil probieren je nachdem ob (-) geerdet ist oder nicht

**Comment by xxbyxx** [comment]
Hi, selbes Problem hier. Liegt bei mir definitiv am Hutschienen-Netzteil (Mean Well HDR-15-5). Ich habe testweise ein Steckernetzteil vom Samsung Smartphone benutzt und damit funktioniert es ohne Probleme. 
Woran liegt das genau?

 Hast du eine Kaufempfehlung
 für ein Hutschienen-Netzteil mit dem das nicht passiert?

**Comment by DUSAG0211** [comment]
> Kann gut sein daß da ein Ableitstrom von dem Sensor (GND) über dich auf Erde läuft und er den Finger dadurch nicht erkennt. Evtl. auch anderes Netzteil probieren je nachdem ob (-) geerdet ist oder nicht

Schliesse mich der Frage an: welches Hutschienennetzteil sollte man probieren? Habe auch ein Meanwell hdr im Einsatz

**Comment by ThomaxK** [comment]
Ich hatte das gleiche Problem. Mit einem Handynetzteil direkt am ESP ging es problemlos, mit dem Netzteil der Installation ging es nicht mehr.
Das Problem: Der Sensor braucht für die Fingerdruckerkennung eine GND-Verbindung. Die meisten Niederspannungsnetzeile sind jedoch prinzipiell für einen SELV Stromkreis ausgelegt, bei dem der Sekundärstromkreis nicht geerdet ist. Baut man den Niederspannungsstromkreis auf PELV um, so geht der Fingerabdrucksensor einwandfrei - zumindest bei mir.
Dazu muss einfach der Minuspol der Sekundärseite mit dem Schutzleiter verbunden werden.
![PELV](https://github.com/user-attachments/assets/81a0d017-475c-4740-8d69-c8edb0d6b37e)

**Comment by xxbyxx** [comment]
Danke für die Info! 
Ich verstehe nicht ganz wieso es dann mit dem Handynetzteil klappt. Die Stecker haben ja keinen Schutzleiterkontakt, daher ist die Masse(-) bei einem Steckernetzteil doch nie geerdet oder?

**Comment by DUSAG0211** [comment]
I can confirm that changing to a pelv setup has solved this issue. Even in socks or barefoot i get instant detection
