### ISSUE TITLE
Compile error with AsyncElegantOTA

### ISSUE THREAD

**Issue by ThomaxK** [frickelzeugs/FingerprintDoorbell#97]
I wanted to compile and upload the code via PlatformIO but got following error message:

Library Manager: Installing ayushsharma82/AsyncElegantOTA @ ^2.2.7
UnknownPackageError: Could not find the package with 'ayushsharma82/AsyncElegantOTA @ ^2.2.7' requirements for 
your system 'windows_amd64'

While looking up AsyncElegantOTA, i noticed that there is a newer version 2.2.9. But this didn't work neither.
I tried to update the code to ElegantOTA in async mode, beacause AsyncElegantOTA is deprecated but didn't get it to work.

Can someone help me? Thanks!

**Comment by geronet1** [comment]
I've updated ElegantOTA in my fork:
https://github.com/frickelzeugs/FingerprintDoorbell/pull/98

**Comment by ThomaxK** [comment]
Thank you, works great!
